ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "eventType" TEXT NOT NULL DEFAULT 'Altro';
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "eventDate" TIMESTAMP(3);
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "peopleCount" INTEGER;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "budgetRange" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "supplierTypes" TEXT NOT NULL DEFAULT 'Da valutare';
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "status" "SupplierRequestStatus" NOT NULL DEFAULT 'new_request';
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "internalNotes" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "aiReply" TEXT;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "aiReplyCreatedAt" TIMESTAMP(3);
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "SupplierRequest" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT 'supportoforumevento@gmail.com';
ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "sourcePath" TEXT;
ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "status" "SupportRequestStatus" NOT NULL DEFAULT 'new_request';
ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "SupportRequest" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "EditorialArticle" ADD COLUMN IF NOT EXISTS "slug" TEXT NOT NULL DEFAULT '';
ALTER TABLE "EditorialArticle" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
